[package]
name = "gpu-kernel-proc-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
amd = []

[dependencies]
amdgpu-device-libs-build = { path = "/home/sebi/Downloads/amdgpu-rust/amdgpu-rs/amdgpu-device-libs-build" }
quote = "1"
syn = { version = "2", features = ["full"] }
toml = "1"
