[package]
name = "gpu-kernel-proc-macros"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
edition = "2024"
description = "Proc macros to compile and include GPU kernels"
repository = "https://github.com/Flakebi/amdgpu-rs/tree/main/gpu-kernel-proc-macros"
license = "MIT OR Apache-2.0"
keywords = ["amdgpu", "gpu"]
categories = ["hardware-support"]
include = ["/src", "README.md"]

[lib]
proc-macro = true

[features]
amd = ["dep:amdgpu-device-libs-build"]

[dependencies]
amdgpu-device-libs-build = { version = "0.2", path = "../amdgpu-device-libs-build", optional = true, default-features = false }
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full"] }
toml = "1"
