[package]
name = "default-cpu"
version = "0.1.0"
edition = "2024"
description = "Example launching an amdgpu kernel with HIP"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
hip-runtime-sys = "0.1"
