[package]
name = "gpu-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
gpu-kernel-proc-macros = { version = "0.1", path = "gpu-kernel-proc-macros" }

# CPU dependencies
[target.'cfg(not(any(target_arch = "amdgpu", target_arch = "nvptx64")))'.dependencies]
hip-runtime-sys = "0.1"

# GPU dependencies
[target.'cfg(target_arch = "amdgpu")'.dependencies]
amdgpu-device-libs = "0.1"
