[package]
name = "hostcall-cpu"
version = "0.1.0"
edition = "2024"
description = "Example of the CPU of hostcalls on amdgpu"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
hip-runtime-sys = "0.1"
